Speechify/profiles/urls.py
# from django.urls import path
#
# from Text_to_Voice.profiles.views import DetailProfileView, DeleteProfileView, EditProfileView
#
# urlpatterns = (
#     path('details/', DetailProfileView.as_view(), name='profile-detail'),
#     path("delete/", DeleteProfileView.as_view(), name="delete_profile"),
#     path("edit/", EditProfileView.as_view(), name="edit_profile"),
# )

from django.urls import path, include

from Speechify.profiles.views import ProfileDetailsView, ProfileUpdateView, ProfileDeleteView

urlpatterns = (
    path(
        "profile/<int:pk>/", include([
            path('details/', ProfileDetailsView.as_view(), name='profile-detail'),
            path("delete/", ProfileDeleteView.as_view(), name="delete-profile"),
            path("edit/", ProfileUpdateView.as_view(), name="edit-profile"),
        ])
    ),
)

Speechify/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('profile/', include('Speechify.profiles.urls')),
    path('', include('Speechify.web.urls')),
    path('audiofile/', include('Speechify.voices.urls')),
    path('accounts/', include('Speechify.accounts.urls')),
]

Speechify/profiles/models.py
from django.contrib.auth import get_user_model
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.db import models

from Speechify.accounts.models import TextToVoiceUser
from Speechify.core.models import IHaveUser

UserModel = get_user_model()


def validate_username(username):
    is_valid = all(ch.isalnum() or ch == '_' for ch in username)

    if not is_valid:
        raise ValidationError("Username must contain only letters, digits, and underscores!")


class Profile(IHaveUser, models.Model):

    MAX_FIRST_NAME_LENGTH = 25
    MAX_LAST_NAME_LENGTH = 25

    first_name = models.CharField(
        max_length=MAX_FIRST_NAME_LENGTH,
        null=True,
        blank=True,
    )

    last_name = models.CharField(
        max_length=MAX_LAST_NAME_LENGTH,
        null=True,
        blank=True,
    )

    date_of_birth = models.DateField(
        blank=True,
        null=True,
    )

    profile_picture = models.URLField(
        blank=True,
        null=True,
    )

    GENDER_CHOICES = [
        ('', 'Not Specified'),
        ('M', 'Male'),
        ('F', 'Female'),
    ]

    gender = models.CharField(
        max_length=1,
        choices=GENDER_CHOICES,
        blank=True,
        null=True)

    # user = models.OneToOneField(
    #     UserModel,
    #     primary_key=True,
    #     on_delete=models.CASCADE,
    # )

    @property
    def full_name(self):
        if self.first_name and self.last_name:
            return f"{self.first_name} {self.last_name}"
        return self.first_name or self.last_name

Speechify/profiles/forms.py
from django import forms
from Speechify.profiles.models import Profile


class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ["first_name", "last_name", "date_of_birth", 'gender', "profile_picture"]  # Add other fields as needed

Speechify/profiles/views.py
from django.contrib.auth import get_user_model
from django.urls import reverse_lazy, reverse

from Speechify.core.view_mixins import OwnerRequiredMixin
from Speechify.profiles.forms import ProfileForm
from Speechify.profiles.models import Profile
from django.views import generic as views
from django.contrib.auth import mixins as auth_mixin

UserModel = get_user_model()
#
# def get_profile():
#     return Profile.objects.first()
#
#
# class DetailProfileView(views.DetailView):
#     template_name = "profiles/profile-details.html"
#
#     def get_object(self, queryset=None):
#         return get_profile()
#
#     def get_context_data(self, **kwargs):
#         context = super().get_context_data(**kwargs)
#         context['profile_exists'] = Profile.objects.exists()
#         context['user'] = self.request.user
#         return context
#
#
# class EditProfileView(views.UpdateView):
#     template_name = "profiles/profile-edit.html"
#     queryset = Profile.objects.all()
#     success_url = reverse_lazy("profile-detail")
#
#
# class DeleteProfileView(views.DeleteView):
#     template_name = "profiles/profile-delete.html"
#     success_url = reverse_lazy("index")
#
#     def get_object(self, queryset=None):
#         return get_profile()
#
#     def get_context_data(self, **kwargs):
#         context = super().get_context_data(**kwargs)
#         context['profile_exists'] = Profile.objects.exists()
#         context['user'] = self.request.user
#         return context


class ProfileDetailsView(OwnerRequiredMixin, auth_mixin.LoginRequiredMixin, views.DetailView):  # Add "OwnerRequiredMixin" if needed
    queryset = Profile.objects \
        .prefetch_related('user') \
        .all()

    # we add prefetch_related in order to show the user's email on profile details page without accessing the DB again

    template_name = "profiles/profile-details.html"


class ProfileUpdateView(OwnerRequiredMixin, auth_mixin.LoginRequiredMixin, views.UpdateView):
    # queryset = Profile.objects.all()
    # template_name = "profiles/profile-edit.html"
    # fields = ("first_name", "last_name", "date_of_birth", "profile_picture")

    # OR USING FORM: (just remove get_form method and add get_object method if needed)
    model = UserModel
    form_class = ProfileForm
    template_name = "profiles/profile-edit.html"

    def get_success_url(self):
        return reverse("profile-detail", kwargs={"pk": self.object.pk})

    # def get_form(self, form_class=None):
    #     form = super().get_form(form_class=form_class)
    #
    #     form.fields["date_of_birth"].widget.attrs["type"] = "date"
    #
    #     return form

    # ADD:
    def form_valid(self, form):
        # Ensure that the profile instance is correctly bound to the form data
        form.instance = self.get_object()
        return super().form_valid(form)

    # ADD:
    def get_object(self, queryset=None):
        return self.request.user.profile

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['instance'] = self.get_object()
        return kwargs


class ProfileDeleteView(views.DeleteView):
    # queryset = Profile.objects.all()
    model = Profile
    template_name = "profiles/profile-delete.html"
    success_url = reverse_lazy('index')

templates/profiles/profile-delete.html
{% extends "base.html" %}
{% block main_content %}
    
<div class="wrapper-audio-details">
        <br>
        <br>
        <div class="edit-profile-details">
            <h2>Are you sure you want to delete your profile?</h2>
        </div>
        <br>
    <form action="{% url 'delete-profile' pk=request.user.pk %}" method="post" style="display: inline;">
        
        <div class="form-group-button-audio-edit">
        <button type="submit" class="register" >Delete</button>
        </div>
        <br>
        <div class="profileText">
             <a class="edit-btn" href="javascript:history.back()">Go Back</a>
        </div>
        
        {% csrf_token %}
    </form>
</div>
{% endblock %}

{% block home-page-text %}
{% endblock %}

{#{% extends "base.html" %}#}
{#{% block main_content %}#}
{##}
{#<div class="profileText">#}
{#    <h1>Are you sure you want to delete your profile?</h1>#}
{#    <form method="post">#}
{#        {% csrf_token %}#}
{#        <div class="sure-buttons">#}
{#            <!-- Yes (Delete Profile) Button -->#}
{#            <div class="actionBtn">#}
{#                <button type="submit" class="delete">Yes</button>#}
{#            </div>#}
{#            <!-- Go Back Button -->#}
{#            <a href="javascript:history.back()">Go Back</a>#}
{#        </div>#}
{#    </form>#}
{#</div>#}
{##}
{#{% endblock %}#}
{##}
{#{% block home-page-text %}#}
{#{% endblock %}#}

templates/profiles/profile-details.html
{% extends 'base.html' %}
{% block main_content %}
    <section id="detailsPage">
        <div class="wrapper">
            <div class="profilePage">
                {% if object.profile_picture %}
                    <img src="{{ object.profile_picture }}" alt="img8" />
                {% else %}
                    <img src="https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_960_720.png" alt="img8" />
              {% endif %}
            </div>

            <div>
                <br>
                <!-- User First and Last Name IF Added -->
            <div class="profile-details-page">
                <h2>{{ object.user.email }}</h2>
            </div>
            <br>
            
            <div class="profile-details-infos">
            
                {% if object.first_name %}
                    <p class="email">First name: {{ object.first_name }}</p>
                {% endif %}
                {% if object.last_name %}
                    <p class="email">Last name: {{ object.last_name }}</p>
                {% endif %}
                {% if object.full_name %}
                    <p class="email">Full name: {{ object.full_name }}</p>
                {% endif %}
                <p class="email">Email: {{ object.user.email }}</p>
                {% if object.date_of_birth %}
                    <p class="email">Date of birth: {{ object.date_of_birth }}</p>
                {% endif %}
            
                {% if object.gender %}
                    <p class="email">Gender: {{ object.gender }}</p>
                {% else %}
                    <p class="email">Gender not specified.</p>
                {% endif %}
            </div>
            
            </div>
        
            <div class="profileText">
                {% if object.pk == request.user.pk %}
                    <!-- Link to Edit Profile Page -->
                    <div class="actionBtn">
                        <a href="{% url 'delete-profile' pk=object.pk%}" class="remove">Delete</a>
                        <a href="{% url 'edit-profile' pk=request.user.pk%}" class="remove">Edit</a>
                    </div>
                {% endif %}

            
{#                {% if object.age %}#}
{#                    <h1>Age: {{ object.age }}</h1>#}
{#                {% endif %}#}
{#                <h1>Albums: {{ object.album_set.count }}</h1>#}
            </div>
        </div>
    </section>

{% endblock %}
{% block home-page-text %}
{% endblock %}

templates/profiles/profile-edit.html
{% extends 'base.html' %}

{% load static %}

{% block main_content %}

{#<section id="detailsPage">#}
{#<div class="wrapper">#}
{##}
{#    <div class="edit-delete">#}
{#        <h1>Edit Profile details</h1>#}
{#        <!-- Start Edit Profile From -->#}
{#        <form action="{% url 'edit-profile' pk=object.pk %}" method="post">#}
{#            {{ form.as_p }}#}
{##}
{##}
{#            <!-- Edit Profile Button -->#}
{#            <button type="submit" class="delete">Edit</button>#}
{##}
{#            {% csrf_token %}#}
{#        </form>#}
{#        <!-- End Edit Profile Form -->#}
{#    </div>#}
{##}
{#</div>#}
{#</section>#}
    
<section id="detailsPage">
    <div class="wrapper">


        <div class="profilePage">
            {% if object.profile_picture %}
                <img src="{{ object.profile_picture }}" alt="Profile Picture" />
            {% else %}
                <img src="https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_960_720.png" alt="Default Profile Picture" />
            {% endif %}
        </div>


        <div class="edit-delete">
            <br>
            <div class="edit-profile-details">
                <h2>Edit profile details</h2>
            </div>
            <br>
            <!-- Start Edit Profile Form -->
            <form action="{% url 'edit-profile' pk=object.pk %}" method="post">
                {% csrf_token %}
                <div class="form-group">
                    <!-- First Name -->
                    <div class="form-field">
                        <label for="id_first_name">First Name:</label>
                        {{ form.first_name }}
                    </div>
                    <!-- Last Name -->
                    <div class="form-field">
                        <label for="id_last_name">Last Name:</label>
                        {{ form.last_name }}
                    </div>
                </div>
                <div class="form-group">
                    <!-- Date of Birth -->
                    <div class="form-field">
                        <label for="id_date_of_birth">Date of Birth:</label>
                        {{ form.date_of_birth }}
                    </div>
                    <!-- Gender -->
                    <div class="form-field">
                        <label for="id_gender">Gender:</label>
                        {{ form.gender }}
                    </div>
                </div>
                <div class="form-group">
                    <div class="form-field">
                        <label for="id_profile_picture">Profile Picture:</label>
                        {{ form.profile_picture }}
                    </div>
                </div>

                <div class="form-group-button">
                <button type="submit" class="delete">Edit</button>
                </div>
            </form>
            <!-- End Edit Profile Form -->
        </div>
    </div>
</section>
    
{% endblock %}

{% block home-page-text %}
{% endblock %}